In [1]:
import torch

### `torch.gradient`

In [2]:
# f(x) = x^2
coordinates = (torch.tensor([-2., -1., 1., 4.]),)
values = torch.tensor([4., 1., 1., 16.], )
torch.gradient(values, spacing=coordinates)

(tensor([-3., -2.,  2.,  5.]),)

In [3]:
# [[f(0, 0), f(0, 1), f(0, 2), f(0, 3)], [f(1, 0), f(1, 1), f(1, 2), f(1, 3)]]
t = torch.tensor([[1, 2, 4, 8], [10, 20, 40, 80]])
torch.gradient(t)

(tensor([[ 9., 18., 36., 72.],
         [ 9., 18., 36., 72.]]),
 tensor([[ 1.0000,  1.5000,  3.0000,  4.0000],
         [10.0000, 15.0000, 30.0000, 40.0000]]))

In [4]:
torch.gradient(t, dim=0)

(tensor([[ 9., 18., 36., 72.],
         [ 9., 18., 36., 72.]]),)

In [5]:
torch.gradient(t, dim=1)

(tensor([[ 1.0000,  1.5000,  3.0000,  4.0000],
         [10.0000, 15.0000, 30.0000, 40.0000]]),)

In [6]:
torch.gradient(t, spacing=2.0)

(tensor([[ 4.5000,  9.0000, 18.0000, 36.0000],
         [ 4.5000,  9.0000, 18.0000, 36.0000]]),
 tensor([[ 0.5000,  0.7500,  1.5000,  2.0000],
         [ 5.0000,  7.5000, 15.0000, 20.0000]]))

In [7]:
torch.gradient(t, spacing=[2., 3.])

(tensor([[ 4.5000,  9.0000, 18.0000, 36.0000],
         [ 4.5000,  9.0000, 18.0000, 36.0000]]),
 tensor([[ 0.3333,  0.5000,  1.0000,  1.3333],
         [ 3.3333,  5.0000, 10.0000, 13.3333]]))

In [8]:
coords = (torch.tensor([0, 2]), torch.tensor([0, 3, 6, 9]))
torch.gradient(t, spacing=coords)

(tensor([[ 4.5000,  9.0000, 18.0000, 36.0000],
         [ 4.5000,  9.0000, 18.0000, 36.0000]]),
 tensor([[ 0.3333,  0.5000,  1.0000,  1.3333],
         [ 3.3333,  5.0000, 10.0000, 13.3333]]))

### `torch.autograd`

In [10]:
x = torch.tensor(2.0, requires_grad=True)
y = 5 * x ** 3 - x ** 2 + 4

y.backward()
print(x.grad)

tensor(56.)
